### ISSUE TITLE
Error on execute

### ISSUE THREAD

**Issue by rafaelstz** [IonicaBizau/gh-notifier#2]
![image](https://cloud.githubusercontent.com/assets/610598/12264602/0c7156ee-b91f-11e5-9827-13ffa128622c.png)

**Comment by IonicaBizau** [comment]
Can you give me the output of `node --version`?

**Comment by rafaelstz** [comment]
v0.12.9

**Comment by IonicaBizau** [comment]
@rafaelstz That's the issue. You need to upgrade to `>=4.0.0`. You can use [`nvm`](https://github.com/creationix/nvm) to do that. :arrow_up:

**Comment by rafaelstz** [comment]
Thanks! :smile:

**Comment by IonicaBizau** [comment]
You're welcome! :+1:
